### PR TITLE
Message shutdown request

### PR DESCRIPTION
**Pull request by yorickdewid**
Sorry for the `src/msg.c:39` indentation

### CODE REVIEW

**Comment by jorisvink** [comment]
Could you update the messaging example to include a handler such as /shutdown that demonstrates this?

**Comment by yorickdewid** [comment]
See update, I'll update the generic example with a `http_server_version` as well in a new PR.

**Comment by jorisvink** [comment]
Fix the indentation while you're at it so this PR is complete.

I will merge this in later tonight then.

**Comment by jorisvink** [comment]
One last nitpick, sorry I didn't notice this before.

The new shutdown functionality is hidden behind !defined(KORE_NO_HTTP) which means if I build this with NOHTTP=1 I no longer get this functionality even though the messaging framework is still available :)

Maybe a good idea to move out this of these defines so it is still available under those scenarios.

.joris

**Comment by yorickdewid** [comment]
No problem, happy to do it. More PRs and Issues coming up :)

**Comment by jorisvink** [comment]
Neat. Thanks a bunch.

**Pull request merged**
