### PR TITLE
SHA256 checksum on modules

### PR DESCRIPTION
**Pull request by jaromil**
A new 'checksum' directive in conf files now accepts the path to .so file and its sha256sum.
The checksum is compared to the matching module among already loaded modules.
The module is removed from the loaded list if the checksum is not matching.

### CODE REVIEW

**Comment by jaromil** [comment]
PR is rebased with modifications to address all issues raised in past conversation on IRC.

Last standing issue perhaps the flag, as is your intention to re-use it also for signed modules: should it change to `defined(KORE_INTEGRITY)` then?

**Comment by jorisvink** [comment]
Neat, thanks @jaromil I will take a look at soon as I get back from vacation.

Yes, try putting it behind an INTEGRITY build option.

**Comment by jaromil** [comment]
headsup noticing your cleanup ;^) I'll add the last INTEGRITY build flag anytime soon this week

**Comment by jaromil** [comment]
INTEGRITY=1 is there now also in docs so this is basically ready unless you have other remarks.
I'm pretty happy with it, tested and using it already.

**Comment by jorisvink** [comment]
@jaromil Yup!

**Comment by jaromil** [comment]
Following up on your work on single binaries, this is now obsoleted.

At least for my own use-case I'll be using single binaries. thanks

**Pull request closed without merging**
