### PR TITLE
maint - adding tests and check target to makefile

### PR DESCRIPTION
**Pull request by sinemetu1**
Hey Joris,

This is a start for adding tests. I've got some pretty basic tests for all the functions in `buf.c` here and also added travis-ci  [here](https://travis-ci.org/sinemetu1/kore). There are a lot more tests to add for the rest of the framework but I just wanted to get some feedback before I get too far. Please let me know if there's anything particularly glaring here.

Thanks.

### CODE REVIEW

**Comment by jorisvink** [comment]
Running a make check on the tld of the tree results in the following warnings/errors being spewed out.

```
joris@treo kore % make check
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -g -DPREFIX='"/usr/local"' -D_GNU_SOURCE=1 -DKORE_TEST -DKORE_PEDANTIC_MALLOC -c tests/test.c -o tests/test.o
In file included from tests/test.c:20:0:
tests/test-buf.c: In function 'test_kore_buf_append':
tests/test-buf.c:39:23: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
tests/test-buf.c: In function 'test_kore_buf_appendb':
tests/test-buf.c:58:24: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
tests/test-buf.c:62:24: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
tests/test-buf.c: In function 'test_kore_buf_appendf':
tests/test-buf.c:85:23: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
tests/test-buf.c: In function 'test_kore_buf_release':
tests/test-buf.c:110:23: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
tests/test-buf.c: In function 'test_kore_buf_replace_string':
tests/test-buf.c:140:31: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
tests/test-buf.c:140:51: warning: cast discards '__attribute__((const))' qualifier from pointer target type [-Wcast-qual]
In file included from tests/test.c:21:0:
tests/test-utils.c: In function 'test_kore_strtonum':
tests/test-utils.c:166:2: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'long long int' [-Wformat]
tests/test-utils.c:166:2: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'long long int' [-Wformat]
tests/test-utils.c: In function 'test_kore_split_string':
tests/test-utils.c:234:2: error: 'for' loop initial declarations are only allowed in C99 mode
tests/test-utils.c:234:2: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [tests/test.o] Error 1
```

I suggest you take a good look at the code and fix these issues.

**Comment by sinemetu1** [comment]
@jorisvink It looks like the linking is not right in the gcc build on travis. I fixed the c99 `for initilization issue`. I'm also not sure why the `PRIu64` macro seems to not be working on these builds. I tried on my system with both clang and gcc and I can't reproduce the issue. :(

**Comment by jorisvink** [comment]
Seems it might be some linker issue related to the ordering of the libs you are linking against for the test code.

**Comment by sinemetu1** [comment]
@jorisvink I think the travis build/tests are all cleaned up now. Let me know if there are any other changes you'd like for this to get merged. :)

**Comment by jorisvink** [comment]
Hey, cool I'll take a look at this later or tomorrow!

.joris

**Comment by jorisvink** [comment]
Haven't forgotten to look at it, have you tried this on OSX or any of the BSDs?

.joris

**Comment by sinemetu1** [comment]
It works on OSX. I don't have a BSD system to test on.

**Comment by jorisvink** [comment]
OK, I'll run this through one.

**Comment by jaromil** [comment]
I've cloned @sinemetu1's branch, rebased it to master and tested on FreeBSD ###.enemy.org 10.3-RELEASE-p4, no problems compiling, prints these results:

```
./kore-test
Running test_kore_buf_append...
expected == actual?: a test value == a test value
Running test_kore_buf_appendb...
expected == actual?: buf 1buf 2 == buf 1buf 2
Running test_kore_buf_appendf...
expected == actual?: a test value a b c d == a test value a b c d
Running test_kore_buf_release...
expected == actual?: buf 1 == buf 1
Running test_kore_buf_replace_string...
expected == actual?: a string replaced == a string replaced
Running test_kore_time_to_date...
expected == actual?: Sun, 04 Jan 2015 13:35:27 GMT == Sun, 04 Jan 2015 13:35:27 GMT
Running test_kore_time_ms...
Running test_kore_base64_encode...
expected == actual?: aHR0cDovL2tvcmUuaW8= == aHR0cDovL2tvcmUuaW8=
Running test_kore_base64_decode...
expected == actual?: http://kore.io == http://kore.io
Running test_kore_strtonum64...
Running test_kore_strtonum...
Running test_kore_snprintf...
expected == actual?: an expected string == an expected string
Running test_kore_strlcpy...
expected == actual?: an expected string == an expected string
Running test_kore_split_string...
expected == actual?: a  == a 
expected == actual?:  b  ==  b 
expected == actual?:  c ==  c
```
Needless to say, I'd be very much in favor of having this included, even if pending fix for BSD.

**Comment by jorisvink** [comment]
This is so old and stale I'm closing it.

**Pull request closed without merging**
