### PR TITLE
http query params are possible in post requests too

### PR DESCRIPTION
**Pull request by Houdini**

### CODE REVIEW

**Comment by jorisvink** [comment]
I agree but maybe http_populate_get() is no longer the correct name for this as it's only looking at the query string.

**Comment by Houdini** [comment]
Agree. But I am not fan of breaking changes.
Should we done this with some kind of deprecation warning?

Better name is:
http_populate_query_params

**Comment by jorisvink** [comment]
Break it, it is OK. I like the new name.

This opens up a new can of worms however: param blocks in configurations.

Right now you have a param block specifying the method + parameters to be validated in the configuration. (param get / { } or param post / {} for example). These changes should probably
be reflected in the param blocks as well as get turns more into "this is allowed in the query string".

This will come with changes to http_argument_add() to specify wether or not the argument came from the query string or a method defined in the configuration so we can find the correct param block and call the correct validator.

**Comment by jorisvink** [comment]
A very delayed response, but I actually have a sane solution for this. I will most likely push this out tomorrow.

It basically allows you to mark params {} block with being for query strings or not regardless of the HTTP method configured for them.

Eg:
```
params qs:get / {
    ....
}

# allowed parameters in the query string for POSTs
params qs:post / {
    ....
}

# allowed parameters in the POST body for www-encoded
params post / {
    ....
}
```

**Comment by jorisvink** [comment]
Fix commited.

**Pull request closed without merging**
