### PR TITLE
correct buffer reset

### PR DESCRIPTION
**Pull request by PauloMelo**
The buffer was not correctly emptied not working properly on functions that expect zero terminated strings.

### CODE REVIEW

**Comment by jorisvink** [comment]
I'm not sure I would want this idiom to go through. A struct kore_buf does not represent a C string.

Having offset being set to 0 is more then sufficient to reuse the buffer again with its offset member denoting the actual length afterwards. At least thats how I use it.

.joris

**Comment by PauloMelo** [comment]
Yes that is correct if used on functions where you pass the length, but sometimes people forget to set the end of string character, and use the pointer directly without passing the length and then you may pass more info that you want... I've seen this happen on the PQexec where you only send the pointer for the query.

**Comment by jorisvink** [comment]
Yes, but the parameter to PQexec shouldn't be a kore_buf->buf pointer unless it was written to with kore_buf_appendf() which NUL terminates its result (see printf and family).

.joris

**Comment by PauloMelo** [comment]
Well I've seen that on this code:
```
   struct kore_buf *query;
    query = kore_buf_create(200);
   
    kore_buf_appendf(query, "UPDATE tbusers SET userlastlogin=%lu WHERE userid=%u;", currentTime, user->userID);
    if (!kore_pgsql_query_sync(pgsql, (char *)query->data)) {
        kore_log(LOG_NOTICE, "Query failed: %s %s\n", pgsql->error, query->data);
    }
    kore_buf_reset(query);
    kore_buf_appendf(query, "DELETE FROM tbuserolympus WHERE userid=%u;",user->userID);
    if (!kore_pgsql_query_sync(pgsql, (char *)query->data)) {
        kore_log(LOG_NOTICE, "Query failed: %s %s\n", pgsql->error, query->data);
    }
    kore_buf_reset(query);
    kore_buf_appendf(query, "INSERT INTO tbuserolympus (usersession, userid, userkey, expiryts) VALUES(decode('%s','hex'),%u,decode('%s','hex'),%lu);", ssid, user->userID, key, expiryTS);  
    if (!kore_pgsql_query_sync(pgsql, (char *)query->data)) {
        kore_log(LOG_NOTICE, "Query failed: %s %s\n", pgsql->error, query->data);
    }  
```

I was having a problem on the delete because it was not nul terminated and at the log I got DELETE FROM tbuserolympus WHERE userid=2 WHERE userid=2;
the second WHERE was from the first query.

**Comment by jorisvink** [comment]
Yes you are right. I was mistaken about my own code. The kore_buf_appendf() function does not copy the NUL terminator from the result into the buffer. Honestly calling kore_buf_appendf() should do this.

I think that is the better fix instead of relying on kore_buf_reset():

Have kore_buf_appendf() copy up to l + 1 bytes so it includes the NUL terminator as well. This way calling kore_buf_appendf() gives you a guarantee the result is NUL terminator if you wish to directly deference the struct kore_buf and use the data pointer as a C string.

While I said earlier kore_buf's are not C strings, calling a function that mimics the printf() family should behave as such.

.joris

**Comment by PauloMelo** [comment]
Yes I agree, I did not know it was intended to kore_buf_appendf to add the NUL, so instead I corrected on a function defined by me in the past. 

But it will be way better to be on the kore_buf_appendf.
You may discard the commit c362486

The other commit is the sync stuff. Here I only added two functions one for initializing the struct kore_pgsql and similar to the pgsql_prepare without the async and job stuff.
The kore_pgsql_query_sync runs as discussed before, and finally kore_pgsql_cleanup should be called. 
Here I needed to short circuit the job stuff to avoid crashed so whenever the job pointer is NUL it means the kore_pgsql structure belongs to a sync job and so all the event and job related actions are not to be run.

For my sync tests for now it is running perfectly. I did not test the async stuff yet but since there are not substantial changes it should not fail. Perhaps you have some async calls that you can test.

Regards,
Paulo

**Comment by jorisvink** [comment]
Probably better to close this pull issue, and create a new one introducing the pgsql changes, and one that fixes the kore_buf_appendf() function. It gets confusing with mixed diffs.

**Comment by PauloMelo** [comment]
OK

**Pull request closed without merging**
