### PR TITLE
BSD required AF_INET* headers

### PR DESCRIPTION
**Pull request by yorickdewid**
That needed quite some git magic to back on track :)

### CODE REVIEW

**Comment by jorisvink** [comment]
Thanks - wish there was a CI target for BSD so I wouldn't have to always remember to build my diffs everywhere..

**Comment by yorickdewid** [comment]
Yeah there are quite a few more memory errors on BSD, haven't had the time to track them down, but suspect it may have something to do with user permissions.

**Comment by jorisvink** [comment]
Memory errors?

**Comment by yorickdewid** [comment]
Some deallocation errors
```
 109 bytes in 11 blocks are still reachable in loss record 2 of 5
    at 0x4C226B0: malloc (in /usr/local/lib/valgrind/vgpreload_memcheck-amd64-freebsd.so)
    by 0x54CF98F: strdup (in /lib/libc.so.7)
    by 0x411D61: kore_pool_init (pool.c:41)
    by 0x40F141: kore_mem_init (mem.c:66)
    by 0x406474: main (kore.c:163)

 352 bytes in 11 blocks are still reachable in loss record 3 of 5
    at 0x4C23BA0: calloc (in /usr/local/lib/valgrind/vgpreload_memcheck-amd64-freebsd.so)
    by 0x411E6D: pool_region_create (pool.c:141)
    by 0x411E00: kore_pool_init (pool.c:53)
    by 0x40F141: kore_mem_init (mem.c:66)
    by 0x406474: main (kore.c:163)
```
Although I think these they are not related to BSD.

This is probably going well on Linux, BSD reports bound errors:

```
 Invalid read of size 8
    at 0x54A2740: setproctitle (in /lib/libc.so.7)
    by 0x41E471: kore_platform_proctitle (bsd.c:274)
    by 0x40691E: kore_server_start (kore.c:430)
    by 0x40662E: main (kore.c:217)
  Address 0x7fffffffefe0 is not stack'd, malloc'd or (recently) free'd
```

**Comment by jorisvink** [comment]
The first two are a the pools backing kore_malloc() and family that are never destroyed on exit.

The second one is valgrind being weird because there's nothing wrong with that code. It's a kore_platform_proctitle("kore [parent]"); call which on BSD leads to setproctitle("%s", title);

.joris

**Pull request merged**
