### PR TITLE
Add methods to init/destroy kore_buf without allocating/freeing it

### PR DESCRIPTION
**Pull request by raphaelmonrouzeau**
Adds kore_buf methods to init/destroy them without allocating/deallocating them

### CODE REVIEW

**Comment by jorisvink** [comment]
So now we have kore_buf_init() and kore_buf_destroy(), excellent.

The problem I am seeing is that there is nothing stopping someone from accidentally doing a kore_buf_init(&buf); followed by a kore_buf_release(&buf).

kore_buf_release() will call kore_mem_free() on the passed kore_buf, which if that resides on a stack somewhere is obviously going to have a bad day. Same goes for kore_buf_free().

**Comment by raphaelmonrouzeau** [comment]
True. The problem's mostly with kore_buf_release and kore_buf_appendb (which calls kore_buf_release).

I would propose to withdraw the call to kore_mem_free of kore_buf_release and add one where necessary in the code base. What do you think ?

**Comment by jorisvink** [comment]
Honestly there is no need for the kore_buf data structure to be in the hands of the buf API this was a wrong choice of mine at the beginning and should just be fixed.

I'd say let the developer decide where it lives:

* Replace kore_buf_release() with a kore_buf_data() call that returns a const pointer to the data and the length of said data.
* Kill off kore_buf_appendb(), this can be solved with the tools provided in a better way.
* Kill off kore_buf_free() and kore_buf_create().

**Comment by raphaelmonrouzeau** [comment]
OK to me.

**Comment by jorisvink** [comment]
This is a pretty involved change, I'll be doing this swap somewhere today or tomorrow.

Please keep the PR up for now.

**Comment by jorisvink** [comment]
I'm going to refrain from making my suggested changes and instead approach this a bit different. Your new functions are solid and I will merge those in soon.

**Comment by jorisvink** [comment]
I've made a bunch of changes:

- kore_buf_create() is now kore_buf_alloc().
- you can safely use kore_buf_release() on buffers not allocated by the API.

**Pull request merged**
