### PR TITLE
Contain the kore.

### PR DESCRIPTION
**Pull request by thorduri**
Bit of a chicken and egg problem to start using these as nothing is alive on the hub yet.

Some bikeshedding needs to take place regarding names and tags.

### CODE REVIEW

**Comment by jorisvink** [comment]
This is the initial approach as I understood it.
Once this is merged in, some other stuff needs to happen right?

Can you explain here what that other stuff would be?

**Comment by jorisvink** [comment]
Don't forget to open an issue describing the general approach for Dockerizing Kore applications ;)

**Comment by Geenz** [comment]
I kind of have to wonder here, why Docker instead of something like Vagrant?  To my knowledge, and do correct me if I'm wrong here, Docker only natively works under Linux, while on everything else you have to use something like Boot2Docker.

This seems like an issue given that Boot2Docker only seems to support Windows and OS X, while BSD OSes such as OpenBSD and FreeBSD aren't supported as of yet. So I would question whether or not Kore would need to also support the virtualization methods built into the BSDs to make up for the lack of Docker support on those OSes, or if something like Vagrant would be a better choice.

There's also the option of neither being supported directly within Kore, but rather being maintained externally via Docker and Vagrant files that one could just drop into their projects.  I've managed to do a Vagrant-based setup that has its own bootstrap scripts for a FreeBSD based guest within a Kore project.

**Comment by jorisvink** [comment]
Nearly made it :-)

It is not really Docker instead of Vagrant. I have no objections against either. I'd like to contain useful things for Kore deployment within the repository as to help build the images or example setup of deployment processes.

> I've managed to do a Vagrant-based setup that has its own bootstrap scripts for a FreeBSD based guest within a Kore project

That is neat I'd love to see how that's done!

**Comment by Geenz** [comment]
> That is neat I'd love to see how that's done!

In that case, I'll see about doing a pull request with a Vagrant example either later today or tomorrow.

**Comment by thorduri** [comment]
See https://github.com/jorisvink/kore/pull/30/

The usable matrix for Vagrant is quite large, bunch of providers then which
OS/Distro and what provisioner to use ?

All of which are less usefull then docker out of the box.

Keep in mind that the toplevel Dockerfile was probably a mistake, I use one
for development and probably shouldn't have included it in the PR now that
I come to think about it.

On Thu, May 21, 2015 at 2:19 PM, Geenz <notifications@github.com> wrote:

> That is neat I'd love to see how that's done!
>
> In that case, I'll see about doing a pull request with a Vagrant example
> either later today or tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jorisvink/kore/pull/62#issuecomment-104253189>.
>



-- 
/ciao, thorduri.

**Pull request merged**
