### PR TITLE
C++ Support

### PR DESCRIPTION
**Pull request by Geenz**
This pull request brings minimal C++ support via the KORE_CPP_SUPPORT environment variable.

I've included an example.  It should be pretty straight forward.

### CODE REVIEW

**Comment by jorisvink** [comment]
It seems that the wrong compiler is being used for C++ files. See cli.c:1037 you are still passing compiler instead of cppcompiler for example.

Found when testing under OpenBSD, which btw do does not understand c++11 as a standard so it does not work out of the box with the default compiler.

**Comment by Geenz** [comment]
Ah, staying up for nearly 24 hours tends to result in typos like that.

What compiler is OpenBSD running nowadays?  I would have assumed it made the switch to clang along with FreeBSD at least a couple of years ago.

**Comment by Geenz** [comment]
I've added support for selecting your own dialect through the CPPSTD environment variable when you build a project using kore.  I've also included a new CPPLIB environment variable to override the default C++ library that's used.

So for example, say I want to compile with clang, using C++11, and LLVM's libc++:
```
# env CXX=clang++ CXXSTD=c++11 CXXLIB=c++ kore build
```

**Comment by jorisvink** [comment]
Cool.

Thinking about this though, I was wondering if this should not be a simplified "always-on" feature as there's not a lot of munging going on in the core components.

GCC and clang automatically invoke their C++ parts if they are compiling a file with .cpp or whichever C++ file extension. (They do not however link explicitly against libstd++).

This means that simply picking up any .cpp files while building the file list in the cli code could work if we properly recognise them ourselves as C++ and enable linking against libstd++ in the linker phase.

This would kill all the almost duplicate code like cli_compile_cppfiles and the likes.

Having this always enabled shouldn't hurt non C++ users at all.

**Comment by Geenz** [comment]
I agree that an ideal scenario would be to have it "always on", but at the same time I almost feel that for that scenario it'd also be worth considering adding wrappers for relevant data structures and functionality, which to a degree falls outside of the scope of this PR.

As far as the combining of cli_compile_cppfile into cli_compile_cfile, I feel the two should remain separate since for C++ there's a couple of warnings that get enabled that don't really apply to C, not to mention the dialect options will cause clang and GCC to throw an error if used on a C file.  But for file discovery, I agree that duplicates for that should be removed in an always on scenario.

**Comment by jorisvink** [comment]
> I agree that an ideal scenario would be to have it "always on", but at the same time I almost feel that for that scenario it'd also be worth considering adding wrappers for relevant data structures and functionality, which to a degree falls outside of the scope of this PR.

I am not sure I agree. The whole point of this was to at least in some way enable C++ for modules. Having this as an always available feature seems totally sensible, even without wrappers available. It provides developers (like yourself) the ability to get going in C++ with minimal C glue in your module.

> As far as the combining of cli_compile_cppfile into cli_compile_cfile, I feel the two should remain separate since for C++ there's a couple of warnings that get enabled that don't really apply to C, not to mention the dialect options will cause clang and GCC to throw an error if used on a C file. But for file discovery, I agree that duplicates for that should be removed in an always on scenario.

You could always hack the cfile data structure to include some flag denoting if its a C or C++ file and automagically add the correct compiler flags at the build stage. =)

**Comment by Geenz** [comment]
I suppose that wrappers can happen later.  It's just a thought to provide additional convenience, not necessarily something that's totally necessary.

As far as mucking about with the cfile structure, I suppose that's fair.  I'll go ahead and do that.

**Comment by jorisvink** [comment]
Great.

So we can for now kill off the KORE_CPP_SUPPORT and remove linking against libstdc++ for Kore as well. The libstdc++ linkage should be done at module link time.

Perhaps sensible to retain the environmental variables (CXX, CXXSTD etc).

**Pull request merged**
